### ISSUE TITLE
How to develop self-defined operator and aggregate into tflite micro

### ISSUE THREAD

**Issue by LixiangHan** [etrommer/dcsr#1]
Hi Elias,

I am trying to add the self-defined operator and data structure into tflite micro, similar with your project. I have no idea how I can do that. I have developed my own operator like what cmsis-nn does. Could you give me some advice about how to aggregate it into tflite micro.

Thank you.

Best,
Lixiang

**Comment by etrommer** [comment]
Hi Liaxing,
there are several steps to this. Here's the outline of my general approach:
1. Use training, pruning and model conversion facilities from Tensorflow/Tensorflow lite without changes. This creates a vanilla .tflite model that has dense tensors with lots of zeroes. Benefit of this is that is that I don't have to mess with the internal Tensorflow lite model conversion flow.
2. The [conversion script](https://github.com/etrommer/dcsr/blob/main/conversion/compress_tflite.py) ingests the .tflite model, identifies sparse weight tensors and converts them to a custom data structure. If you want to add data structures in this step, this means that you will need to adapt the Flatbuffer schema and generate Python bindings for the new schema using this command: `flatc -p --gen-object-api schema.fbs`. The updated flatbuffer data structure is then written out as a new .tflite model
3. In order for tflite micro to interpret your new data fields, you need to generate updated C++ bindings from your schema. This should be the correct command, but better double-check: `flatc -c --gen-object-api --no-union-value-namespacing schema.fbs`
4. Unfortunately, tflite micro does not automatically read the data from the updated Flatbuffer, therefore you have to make sure that it gets pushed through its internal data structures. I have piggy-backed my data onto the already existing `TfLiteSparsity` data structure here: https://github.com/etrommer/dcsr/blob/662346603fb0720565b00c4caf53ba47adb9ee57/m55_inference/tensorflow/lite/c/common.h#L394-L409
5. Last step is to make sure that your new data structure actually gets populated from the Flatbuffer data during the allocation stage. This happens here: https://github.com/etrommer/dcsr/blob/662346603fb0720565b00c4caf53ba47adb9ee57/m55_inference/tensorflow/lite/micro/micro_allocator.cc#L569-L599
6. You should then have your additional metadata available as part of the normal Tensor struct. I don't have dedicated operators but check at runtime whether my custom sparsity data structure is present. If it is, the operation gets passed on to a sparse kernel version. If it is not, the normal kernel is used: https://github.com/etrommer/dcsr/blob/662346603fb0720565b00c4caf53ba47adb9ee57/m55_inference/tensorflow/lite/micro/kernels/cmsis_nn/conv.cc#L370-L401

I hope this helps!

Edit: One thing to be aware of is that the data in each tflite tensor in the updated model is not consistent with the tensor's shape anymore. Not a problem in itself, just be aware that it crashes [Netron](https://netron.app/) if you want to use it to inspect your model 😄

**Comment by LixiangHan** [comment]
Hi Elias,

What you shared is very helpful.
I am now sucked on how to save the modified tflite model. There seems to be an issue with that part of your code.
https://github.com/etrommer/dcsr/blob/24d36cc5069707ab6c9c94e78e7e225e4c014fee/conversion/compress_tflite.py#L36-L37

Update:
Modified code works well
 ```python
def save_model(model, fh):
    fh.write(model)
```
Really really thanks for your help😄😄

Best,
Lixiang

**Comment by etrommer** [comment]
Happy to hear! :smiley: 
Thank you for pointing out the bug! I guess this is one of the cases where CI would have come in handy...

**Comment by LixiangHan** [comment]
Hi Elias,

Sorry for bothering you again. 🥲

I have a problem that is not so relevant to your project, but I think you might know.

I used PMU to measure the inference time just like what you did, but `ARM_PMU_Get_CCNTR()` always returns `0`. I have set `cpu0.has_pmu=1`  in config.txt. It still does not work. Is there any other setting required to enable PMU for FVP-Corstone-300?

Best,
Lixiang

**Comment by etrommer** [comment]
I remember struggling with this as well, but never properly documented it, as I did early development on the MPS2 where this worked and then moved on to the FPGA board for performance measurements. I think it is connected to some non-obvious option in the config file.

Can you try setting the debug level to 2?
https://github.com/etrommer/dcsr/blob/24d36cc5069707ab6c9c94e78e7e225e4c014fee/m55_inference/config.txt#L23
That might fix it. I will try to reproduce it when I have the time.

Also be aware that the cycle count on the FVP is not terribly helpful for assessing performance, as it seems to only count instructions but does not account for the speed of memory interfaces, the scatter/gather unit etc.

**Comment by LixiangHan** [comment]
> 

Got it! Thank you for so quick reply. Let me try it.👌

Update:
This does work!
